# Generated by Django 5.2.12 on 2026-03-29 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=150)),
                (
                    "ticker",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Acao", "Ação"),
                            ("FII", "Fundo Imobiliário"),
                            ("RendaFixa", "Renda Fixa"),
                            ("Cripto", "Criptomoeda"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ativo",
                "verbose_name_plural": "Ativos",
            },
        ),
        migrations.CreateModel(
            name="Ordem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("Compra", "Compra"), ("Venda", "Venda")], max_length=6
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=8, max_digits=18)),
                ("preco", models.DecimalField(decimal_places=8, max_digits=18)),
                (
                    "taxas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("data", models.DateField()),
                ("resgatar_para_orcamento", models.BooleanField(default=False)),
                (
                    "ativo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordens",
                        to="investimentos.ativo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordem",
                "verbose_name_plural": "Ordens",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="Rendimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("data", models.DateField()),
                ("descricao", models.CharField(blank=True, max_length=255, null=True)),
                ("resgatar_para_orcamento", models.BooleanField(default=False)),
                (
                    "ativo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rendimentos",
                        to="investimentos.ativo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rendimento",
                "verbose_name_plural": "Rendimentos",
                "ordering": ["-data"],
            },
        ),
    ]
