# Generated by Django 5.2.12 on 2026-04-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investimentos", "0002_metafinanceira_metaparcelamensal"),
    ]

    operations = [
        migrations.AddField(
            model_name="ativo",
            name="percentual_alvo",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="ativo",
            name="preco_medio",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="ativo",
            name="quantidade_atual",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
    ]
