# Generated by Django 5.2.12 on 2026-04-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investimentos", "0003_ativo_percentual_alvo_ativo_preco_medio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AportePatrimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data", models.DateTimeField(auto_now_add=True)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "descricao",
                    models.CharField(default="Aporte via Orçamento", max_length=255),
                ),
                ("id_transacao_origem", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Aporte Patrimonial",
                "verbose_name_plural": "Aportes Patrimoniais",
                "ordering": ["-data", "-created_at"],
            },
        ),
    ]
