# Generated by Django 5.2.12 on 2026-04-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investimentos", "0004_aportepatrimonial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ativo",
            name="setor",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
    ]
