# Generated by Django 5.2.12 on 2026-03-29 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContaBancaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=150)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ContaCorrente", "Conta Corrente"),
                            ("Poupanca", "Poupança"),
                            ("Carteira", "Carteira"),
                            ("Corretora", "Corretora"),
                            ("CartaoCredito", "Cartão de Crédito"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "saldo_inicial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "limite_credito",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "dia_vencimento",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "dia_fechamento",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Conta Bancária",
                "verbose_name_plural": "Contas Bancárias",
            },
        ),
        migrations.CreateModel(
            name="PlanoConta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=150)),
                (
                    "tipo_natureza",
                    models.CharField(
                        choices=[
                            ("Receita", "Receita"),
                            ("Despesa", "Despesa"),
                            ("Investimento", "Investimento"),
                            ("Transferencia", "Transferência"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "conta_pai",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcontas",
                        to="contas.planoconta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plano de Conta",
                "verbose_name_plural": "Plano de Contas",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=100)),
                (
                    "cor_hexadecimal",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "plano_conta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tags",
                        to="contas.planoconta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
    ]
