# Generated by Django 5.2.12 on 2026-03-30

from django.db import migrations, models


def preencher_codigos_planos(apps, schema_editor):
    PlanoConta = apps.get_model('contas', 'PlanoConta')

    def atribuir_codigo_recursivo(item, codigo_base):
        item.codigo = codigo_base
        item.save(update_fields=['codigo'])

        filhos = PlanoConta.objects.filter(conta_pai_id=item.id).order_by('id')
        for idx, filho in enumerate(filhos, start=1):
            atribuir_codigo_recursivo(filho, f'{codigo_base}.{idx}')

    raizes = PlanoConta.objects.filter(conta_pai__isnull=True).order_by('id')
    for idx, raiz in enumerate(raizes, start=1):
        atribuir_codigo_recursivo(raiz, str(idx))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoconta',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.RunPython(preencher_codigos_planos, noop_reverse),
        migrations.AlterField(
            model_name='planoconta',
            name='codigo',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
    ]
