# Generated by Django 5.2.12 on 2026-03-30 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0002_planoconta_codigo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planoconta",
            name="codigo",
            field=models.CharField(
                db_index=True,
                max_length=40,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Use formato hierárquico numérico, como 1, 1.1 ou 1.1.1.",
                        regex="^\\d+(\\.\\d+)*$",
                    )
                ],
            ),
        ),
    ]
