# Generated by Django 5.2.12 on 2026-03-29 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contas", "0001_initial"),
        ("orcamento", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LancamentoFuturo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("descricao", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Receita", "Receita"),
                            ("Despesa", "Despesa"),
                            ("Transferencia", "Transferência"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "formato_pagamento",
                    models.CharField(
                        choices=[
                            ("PIX", "PIX"),
                            ("Cartao", "Cartão"),
                            ("Boleto", "Boleto"),
                            ("Dinheiro", "Dinheiro"),
                            ("Debito", "Débito"),
                            ("TED", "TED"),
                            ("DOC", "DOC"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "comprovante",
                    models.FileField(
                        blank=True, null=True, upload_to="comprovantes/futuros/"
                    ),
                ),
                ("data_vencimento", models.DateField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("parcela_atual", models.PositiveIntegerField(blank=True, null=True)),
                ("total_parcelas", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Injetado", "Injetado"),
                            ("Cancelado", "Cancelado"),
                        ],
                        default="Pendente",
                        max_length=10,
                    ),
                ),
                (
                    "cofre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lancamentos_futuros",
                        to="orcamento.cofre",
                    ),
                ),
                (
                    "conta_bancaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lancamentos_futuros",
                        to="contas.contabancaria",
                    ),
                ),
                (
                    "conta_destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lancamentos_futuros_destino",
                        to="contas.contabancaria",
                    ),
                ),
                (
                    "plano_conta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lancamentos_futuros",
                        to="contas.planoconta",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="lancamentos_futuros", to="contas.tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Lançamento Futuro",
                "verbose_name_plural": "Lançamentos Futuros",
                "ordering": ["data_vencimento"],
            },
        ),
        migrations.CreateModel(
            name="Movimentacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Receita", "Receita"),
                            ("Despesa", "Despesa"),
                            ("Transferencia", "Transferência"),
                        ],
                        max_length=15,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "formato_pagamento",
                    models.CharField(
                        choices=[
                            ("PIX", "PIX"),
                            ("Cartao", "Cartão"),
                            ("Boleto", "Boleto"),
                            ("Dinheiro", "Dinheiro"),
                            ("Debito", "Débito"),
                            ("TED", "TED"),
                            ("DOC", "DOC"),
                        ],
                        max_length=10,
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
                (
                    "comprovante",
                    models.FileField(
                        blank=True, null=True, upload_to="comprovantes/movimentacoes/"
                    ),
                ),
                ("data_pagamento", models.DateField(blank=True, null=True)),
                ("data_vencimento", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Efetivado", "Efetivado"),
                            ("Reagendado", "Reagendado"),
                            ("Validado", "Validado/Congelado"),
                        ],
                        default="Pendente",
                        max_length=10,
                    ),
                ),
                (
                    "ciclo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimentacoes",
                        to="orcamento.ciclo",
                    ),
                ),
                (
                    "cofre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimentacoes",
                        to="orcamento.cofre",
                    ),
                ),
                (
                    "conta_bancaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimentacoes",
                        to="contas.contabancaria",
                    ),
                ),
                (
                    "lancamento_pai",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rateios",
                        to="transacoes.movimentacao",
                    ),
                ),
                (
                    "lancamento_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferencia_inversa",
                        to="transacoes.movimentacao",
                    ),
                ),
                (
                    "plano_conta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimentacoes",
                        to="contas.planoconta",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="movimentacoes", to="contas.tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimentação",
                "verbose_name_plural": "Movimentações",
                "ordering": ["-data_vencimento", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransacaoRecorrente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("descricao", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Receita", "Receita"),
                            ("Despesa", "Despesa"),
                            ("Transferencia", "Transferência"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "formato_pagamento",
                    models.CharField(
                        choices=[
                            ("PIX", "PIX"),
                            ("Cartao", "Cartão"),
                            ("Boleto", "Boleto"),
                            ("Dinheiro", "Dinheiro"),
                            ("Debito", "Débito"),
                            ("TED", "TED"),
                            ("DOC", "DOC"),
                        ],
                        max_length=10,
                    ),
                ),
                ("dia_vencimento", models.PositiveSmallIntegerField()),
                ("valor_base", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "tipo_valor",
                    models.CharField(
                        choices=[("Exato", "Exato"), ("Estimado", "Estimado")],
                        default="Exato",
                        max_length=10,
                    ),
                ),
                ("status_ativa", models.BooleanField(default=True)),
                (
                    "cofre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transacoes_recorrentes",
                        to="orcamento.cofre",
                    ),
                ),
                (
                    "conta_bancaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transacoes_recorrentes",
                        to="contas.contabancaria",
                    ),
                ),
                (
                    "conta_destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transacoes_recorrentes_destino",
                        to="contas.contabancaria",
                    ),
                ),
                (
                    "plano_conta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transacoes_recorrentes",
                        to="contas.planoconta",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="transacoes_recorrentes",
                        to="contas.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transação Recorrente",
                "verbose_name_plural": "Transações Recorrentes",
            },
        ),
    ]
