# Generated by Django 5.2.12 on 2026-03-30 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transacoes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lancamentofuturo",
            name="frequencia",
            field=models.CharField(
                choices=[
                    ("Fixa", "Fixa"),
                    ("Variavel", "Variável"),
                    ("Anual", "Anual"),
                ],
                default="Variavel",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="lancamentofuturo",
            name="lancamento_pai",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parcelas_futuras",
                to="transacoes.lancamentofuturo",
            ),
        ),
        migrations.AddField(
            model_name="lancamentofuturo",
            name="lancamento_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="futuro_inverso",
                to="transacoes.lancamentofuturo",
            ),
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="frequencia",
            field=models.CharField(
                choices=[
                    ("Fixa", "Fixa"),
                    ("Variavel", "Variável"),
                    ("Anual", "Anual"),
                ],
                default="Variavel",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="parcela_atual",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="total_parcelas",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transacaorecorrente",
            name="frequencia",
            field=models.CharField(
                choices=[
                    ("Fixa", "Fixa"),
                    ("Variavel", "Variável"),
                    ("Anual", "Anual"),
                ],
                default="Fixa",
                editable=False,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="lancamentofuturo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("Receita", "Receita"),
                    ("Despesa", "Despesa"),
                    ("Investimento", "Investimento"),
                    ("Transferencia", "Transferência"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("Receita", "Receita"),
                    ("Despesa", "Despesa"),
                    ("Investimento", "Investimento"),
                    ("Transferencia", "Transferência"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="transacaorecorrente",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("Receita", "Receita"),
                    ("Despesa", "Despesa"),
                    ("Investimento", "Investimento"),
                    ("Transferencia", "Transferência"),
                ],
                max_length=15,
            ),
        ),
    ]
