# Generated by Django 5.2.12 on 2026-03-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transacoes", "0002_lancamentofuturo_frequencia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lancamentofuturo",
            name="descricao",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="descricao",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="transacaorecorrente",
            name="descricao",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
