# Generated by Django 5.2.12 on 2026-03-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
        ('transacoes', '0003_alter_lancamentofuturo_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentofuturo',
            name='tipo',
            field=models.CharField(
                choices=[
                    ('Receita', 'Receita'),
                    ('Despesa', 'Despesa'),
                    ('Investimento', 'Investimento'),
                    ('Transferencia', 'Transferência'),
                    ('TransfEntrada', 'Transferência - Entrada'),
                    ('TransfSaida', 'Transferência - Saída'),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(
                choices=[
                    ('Receita', 'Receita'),
                    ('Despesa', 'Despesa'),
                    ('Investimento', 'Investimento'),
                    ('Transferencia', 'Transferência'),
                    ('TransfEntrada', 'Transferência - Entrada'),
                    ('TransfSaida', 'Transferência - Saída'),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name='transacaorecorrente',
            name='tipo',
            field=models.CharField(
                choices=[
                    ('Receita', 'Receita'),
                    ('Despesa', 'Despesa'),
                    ('Investimento', 'Investimento'),
                    ('Transferencia', 'Transferência'),
                    ('TransfEntrada', 'Transferência - Entrada'),
                    ('TransfSaida', 'Transferência - Saída'),
                ],
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='conta_destino',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='movimentacoes_destino',
                to='contas.contabancaria',
            ),
        ),
    ]
