# Generated by Django 5.2.12 on 2026-04-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_alter_planoconta_codigo'),
        ('orcamento', '0001_initial'),
        ('transacoes', '0004_movimentacao_conta_destino_and_tipo_transferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoExcluida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_movimentacao_id', models.PositiveIntegerField(db_index=True)),
                ('tipo', models.CharField(choices=[('Receita', 'Receita'), ('Despesa', 'Despesa'), ('Investimento', 'Investimento'), ('Transferencia', 'Transferência'), ('TransfEntrada', 'Transferência - Entrada'), ('TransfSaida', 'Transferência - Saída')], max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('formato_pagamento', models.CharField(choices=[('PIX', 'PIX'), ('Cartao', 'Cartão'), ('Boleto', 'Boleto'), ('Dinheiro', 'Dinheiro'), ('Debito', 'Débito'), ('TED', 'TED'), ('DOC', 'DOC')], max_length=10)),
                ('frequencia', models.CharField(choices=[('Fixa', 'Fixa'), ('Variavel', 'Variável'), ('Anual', 'Anual')], default='Variavel', max_length=10)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('comprovante_path', models.CharField(blank=True, max_length=255)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('parcela_atual', models.PositiveIntegerField(blank=True, null=True)),
                ('total_parcelas', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Efetivado', 'Efetivado'), ('Reagendado', 'Reagendado'), ('Validado', 'Validado/Congelado')], default='Pendente', max_length=10)),
                ('tags_snapshot', models.JSONField(blank=True, default=list)),
                ('excluida_em', models.DateTimeField(auto_now_add=True)),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_excluidas', to='orcamento.ciclo')),
                ('cofre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_excluidas', to='orcamento.cofre')),
                ('conta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_excluidas_origem', to='contas.contabancaria')),
                ('conta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_excluidas_destino', to='contas.contabancaria')),
                ('plano_conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_excluidas', to='contas.planoconta')),
            ],
            options={
                'verbose_name': 'Movimentação Excluída',
                'verbose_name_plural': 'Movimentações Excluídas',
                'ordering': ['-excluida_em', '-created_at'],
            },
        ),
    ]
