# Generated by Django 5.2.12 on 2026-03-29 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ciclo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Planejamento", "Planejamento"),
                            ("Aberto", "Aberto"),
                            ("Fechado", "Fechado"),
                        ],
                        default="Planejamento",
                        max_length=15,
                    ),
                ),
                (
                    "saldo_inicial_projetado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "saldo_final_realizado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Ciclo",
                "verbose_name_plural": "Ciclos",
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Cofre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=150)),
                ("valor_meta", models.DecimalField(decimal_places=2, max_digits=12)),
                ("data_alvo", models.DateField(blank=True, null=True)),
                (
                    "saldo_atual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Andamento", "Em Andamento"),
                            ("Concluida", "Concluída"),
                            ("Pausada", "Pausada"),
                        ],
                        default="Andamento",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cofre",
                "verbose_name_plural": "Cofres",
            },
        ),
        migrations.CreateModel(
            name="MacroOrcamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mes_ano", models.DateField()),
                ("valor_teto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "plano_conta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="macro_orcamentos",
                        to="contas.planoconta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Macro-Orçamento",
                "verbose_name_plural": "Macro-Orçamentos",
                "unique_together": {("mes_ano", "plano_conta")},
            },
        ),
    ]
