# Generated by Django 5.2.12 on 2026-04-02 16:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0003_alter_planoconta_codigo"),
        ("orcamento", "0002_macroorcamento_ano_mes"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovimentacaoOrcamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Receita", "Receita"),
                            ("Despesa", "Despesa"),
                            ("Investimento", "Investimento"),
                            ("Transferencia", "Transferência"),
                        ],
                        max_length=15,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("descricao", models.CharField(blank=True, max_length=255)),
                (
                    "frequencia",
                    models.CharField(
                        choices=[("Mensal", "Mensal"), ("Anual", "Anual")],
                        default="Mensal",
                        max_length=10,
                    ),
                ),
                (
                    "dia_referencia",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "mes_referencia",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                ("status_ativa", models.BooleanField(default=True)),
                (
                    "conta_bancaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimentacoes_orcamento",
                        to="contas.contabancaria",
                    ),
                ),
                (
                    "plano_conta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimentacoes_orcamento",
                        to="contas.planoconta",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="movimentacoes_orcamento",
                        to="contas.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimentação de Orçamento",
                "verbose_name_plural": "Movimentações de Orçamento",
                "ordering": ["tipo", "plano_conta__codigo", "descricao"],
            },
        ),
    ]
